on:
  push:
    branches:
      - main
    paths:
      - 'app/demo/todoapp-svc/**'
  
  workflow_dispatch:
env:
  # CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  CLUSTER_RESOURCE_GROUP: ${{ secrets.CLUSTER_RESOURCE_GROUP }}

# name: Azure ARM
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # Checkout code
    - uses: actions/checkout@main

    # Log into Azure
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        # creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
        parameters: sqlAdminLogin=${{ secrets.AZURE_SQL_ADMIN_LOGIN }} sqlAdminPassword=${{ secrets.AZURE_SQL_ADMIN_PASSWORD }}
        # parameters: app/demo/todoapp-svc/azure-services.parameters.json
        template: app/demo/todoapp-svc/azure-services.bicep 
        failOnStdErr: false

    # AZ feature register for workload identity preview for AKS
    - name: az feature register
      run: |
        az feature register --namespace "Microsoft.ContainerService" --name "EnableWorkloadIdentityPreview"
        
    # Attach ACR to AKS
    - name: attach Azure Container Registry to AKS
      run: |
        CLUSTER_NAME=$(az aks list --resource-group ${{ secrets.CLUSTER_RESOURCE_GROUP }} --query "[].name" -o tsv)
        ACR_NAME=$(az acr list --resource-group ${{ secrets.CLUSTER_RESOURCE_GROUP }} --query "[].name" -o tsv)
        az aks update -n $CLUSTER_NAME -g ${{ secrets.CLUSTER_RESOURCE_GROUP }} --attach-acr $ACR_NAME
